logging:
  level:
    root: INFO 

spring:
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  jpa:
    open-in-view: false

graphql:
  tools:
    schema-location-pattern: schema.graphql